// ─────────────────────────────────────────────────────────────────────────────
//  Atome Bakery — MOP (Method of Production) Data
//  Included as a <script> tag in mops.html and index.html
// ─────────────────────────────────────────────────────────────────────────────

// Mixer capacities in grams
const MIXER_MAX = { large: 150000, small: 60000 };

// Map from product names (as they appear in schedule.json) to MOP id.
// Includes both the short config names AND the full Odoo product names
// (the levain planner uses the raw Odoo label, so both forms are needed).
const PRODUCT_MOP_MAP = {
  // ── Short / config names ──────────────────────────────────────────────────
  "Trad. Baguette":            "trad-baguette",
  "Trad. Baguette (×3)":       "trad-baguette",
  "Trad. Baguette (×1)":       "trad-baguette",
  "Sesame Baguette":           "sesame-baguette",
  "Sesame Baguette (×3)":      "sesame-baguette",
  "Poppy Seed Baguette":       "poppy-baguette",
  "Poppy Seed Baguette (×3)":  "poppy-baguette",
  "Poppy Baguette":            "poppy-baguette",
  "Cheese Baguette":           "cheese-baguette",
  "Cheese Baguette (×3)":      "cheese-baguette",
  "Sourdough Loaf":            "sourdough-loaf",
  "Sourdough Loaf (×2)":       "sourdough-loaf",
  "Ciabatta":                  "ciabatta",
  "Ciabatta (×3)":             "ciabatta",
  "Multigrain Baguette":       "multigrain-baguette",
  "Multigrain Baguette (×3)":  "multigrain-baguette",
  "Country Rye Loaf":          "country-rye",
  "Country Rye Loaf (×2)":     "country-rye",
  "Wholewheat Loaf":           "wholewheat",
  "Wholewheat Loaf (×2)":      "wholewheat",
  "Pizza Dough":               "pizza",
  "Pizza Dough (×2)":          "pizza",
  "Brioche":                   "braided-brioche",
  "Braided Brioche":           "braided-brioche",
  "Brioche Bun":               "brioche-bun",
  "Brioche Buns":              "brioche-bun",
  "Brioche Buns (×3)":         "brioche-bun",
  "Viennoise":                 "viennoise",
  "Viennoise (×2)":            "viennoise",
  "Pain au Chocolat":          "pac",
  "Pain au Chocolat (×3)":     "pac",
  "Liège Waffle":              "waffle",
  "Liège Waffle (×3)":         "waffle",
  "Liege Waffle":              "waffle",
  "Prep mix Braided Brioche":  "braided-brioche",
  "Prep mix Brioche Buns":     "brioche-bun",

  // ── Full Odoo product names (as they appear in schedule.json mix/vac) ─────
  "Pack of 3 Traditional Sourdough Baguette":      "trad-baguette",
  "Pack of 3 Sourdough Sesame Baguette":           "sesame-baguette",
  "Pack of 3 Sourdough Poppy Seed Baguette":       "poppy-baguette",
  "Sourdough Cheese Baguette (Gruyere Cheese)":    "cheese-baguette",
  "Pack of 2 Sourdough Loaves (White Flour)":      "sourdough-loaf",
  "Pack of 3 Ciabatta Sourdough (Sandwich Bread)": "ciabatta",
  "Pack of 3 Multigrain Sourdough Baguette":       "multigrain-baguette",
  "Pack of 2 Country Rye Sourdough Loaf":          "country-rye",
  "Pack of 2 Wholewheat Sourdough Loaf":           "wholewheat",
  "Pack of 2 Pizza Dough":                         "pizza",
  "Brioche (Pastry)":                              "braided-brioche",
  "Pack of 3 Brioche Buns":                        "brioche-bun",
  "Pack of 2 Viennoise (Brioche Baguette)":        "viennoise",
  "Pack of 3 Pain au Chocolat":                    "pac",
  "Pack of 3 Croissant":                           "pac",
  "Pack of 3 Liège Waffle":                        "waffle",
};

// Array of all MOPs
const MOPS = [

  // ── 1. Trad Baguette ──────────────────────────────────────────────────────
  {
    id:            "trad-baguette",
    name:          "Trad Baguette",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 350,
    base_units:    117,
    unit_label:    "baguettes",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 14000, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",                    detail: "Speed 1: 4 min → Speed 2: 8 min. Target dough temp ~26°C. Use Temp Base table for water temp." },
      { phase: "BULK PROOF",             detail: "7000g boxes. First fold while unloading. 1h at ambient temp. Second fold, fridge overnight." },
      { phase: "DIVISION & PRESHAPING",  detail: "Dough divider: 20 pcs / 350g per baguette. Preshape, relax 15–30 min." },
      { phase: "SHAPING",                detail: "Baguette moulder — 14/tray. Scoring: 1 slash." },
      { phase: "FINAL PROOF",            detail: "30 min to 1h at ambient temp." },
      { phase: "FREEZING",               detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 2. Sesame Baguette ────────────────────────────────────────────────────
  {
    id:            "sesame-baguette",
    name:          "Sesame Baguette",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 350,
    base_units:    117,
    unit_label:    "baguettes",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 14000, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
      { name: "Sesame seeds",           g:   400, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",                    detail: "Speed 1: 4 min → Speed 2: 8 min. Target dough temp ~26°C. Use Temp Base table for water temp." },
      { phase: "BULK PROOF",             detail: "7000g boxes. First fold while unloading. 1h at ambient temp. Second fold, fridge overnight." },
      { phase: "DIVISION & PRESHAPING",  detail: "Dough divider: 20 pcs / 350g per baguette. Preshape, relax 15–30 min." },
      { phase: "SHAPING",                detail: "Baguette moulder — 14/tray. Water wash + sesame seed sifting. ⚠️ Allergen: clean all sesame-contact surfaces after use. Scoring: 3 slashes." },
      { phase: "FINAL PROOF",            detail: "30 min to 1h at ambient temp." },
      { phase: "FREEZING",               detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 3. Poppy Seed Baguette ────────────────────────────────────────────────
  {
    id:            "poppy-baguette",
    name:          "Poppy Seed Baguette",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 350,
    base_units:    117,
    unit_label:    "baguettes",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 14000, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
      { name: "Poppy seeds",            g:   400, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",                    detail: "Speed 1: 4 min → Speed 2: 8 min. Target dough temp ~26°C. Use Temp Base table for water temp." },
      { phase: "BULK PROOF",             detail: "7000g boxes. First fold while unloading. 1h at ambient temp. Second fold, fridge overnight." },
      { phase: "DIVISION & PRESHAPING",  detail: "Dough divider: 20 pcs / 350g per baguette. Preshape, relax 15–30 min." },
      { phase: "SHAPING",                detail: "Baguette moulder — 14/tray. Water wash + poppy seed sifting. Scoring: 3 slashes." },
      { phase: "FINAL PROOF",            detail: "30 min to 1h at ambient temp." },
      { phase: "FREEZING",               detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 4. Cheese Baguette ────────────────────────────────────────────────────
  {
    id:            "cheese-baguette",
    name:          "Cheese Baguette",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 350,
    base_units:    117,
    unit_label:    "baguettes",
    note:          null,
    ingredients: [
      { name: "Organic white flour",               g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                             g: 14000, is_flour: false, is_topping: false },
      { name: "Salt",                              g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",             g:  6700, is_flour: false, is_topping: false },
      { name: "Gruyère (2 × 25g sticks/baguette)", g:  5400, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",                    detail: "Speed 1: 4 min → Speed 2: 8 min. Target dough temp ~26°C. Use Temp Base table for water temp." },
      { phase: "BULK PROOF",             detail: "7000g boxes. First fold while unloading. 1h at ambient temp. Second fold, fridge overnight." },
      { phase: "DIVISION & PRESHAPING",  detail: "Dough divider: 20 pcs / 350g per baguette. Preshape, relax 15–30 min." },
      { phase: "SHAPING",                detail: "Hand shaping — insert 2 × 25g gruyère sticks per baguette. 12/tray. Scoring: 3 slashes." },
      { phase: "FINAL PROOF",            detail: "30 min to 1h at ambient temp." },
      { phase: "FREEZING",               detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 5. Sourdough Loaf ─────────────────────────────────────────────────────
  {
    id:            "sourdough-loaf",
    name:          "Sourdough Loaf",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 700,
    base_units:    58,
    unit_label:    "loaves",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 14000, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 4 min → Speed 2: 8 min. ~26°C." },
      { phase: "BULK PROOF",   detail: "7000g boxes. First fold, 1h AT. Second fold, 1h AT. Optionally fridge overnight." },
      { phase: "DIVISION",     detail: "10 pcs / 700g per loaf. No preshape." },
      { phase: "SHAPING",      detail: "Hand shaped — 10 loaves per tray." },
      { phase: "FINAL PROOF",  detail: "30 min to 1h AT. Overnight in fridge. Scoring: 1 slash." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 6. Ciabatta ───────────────────────────────────────────────────────────
  {
    id:            "ciabatta",
    name:          "Ciabatta",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 300,
    base_units:    133,
    unit_label:    "ciabattas",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 12800, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   500, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 4 min → Speed 2: 8 min. ~26°C." },
      { phase: "BULK PROOF",   detail: "6000g boxes. First fold, 1h AT. Second fold, fridge overnight." },
      { phase: "DIVISION",     detail: "20 pcs / 300g per ciabatta. No preshape." },
      { phase: "SHAPING",      detail: "No shaping — place on tray, sprinkle with flour." },
      { phase: "FINAL PROOF",  detail: "Overnight in fridge. No scoring." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 7. Multigrain Baguette ────────────────────────────────────────────────
  {
    id:            "multigrain-baguette",
    name:          "Multigrain Baguette",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 375,
    base_units:    120,
    unit_label:    "baguettes",
    note:          null,
    ingredients: [
      { name: "Organic white flour",                   g: 20000, is_flour: true,  is_topping: false },
      { name: "7 grains mix",                          g:  2100, is_flour: false, is_topping: false },
      { name: "Sunflower seeds",                       g:   500, is_flour: false, is_topping: false },
      { name: "Soaking water for seeds (overnight)",   g:  2700, is_flour: false, is_topping: false },
      { name: "Water",                                 g: 12300, is_flour: false, is_topping: false },
      { name: "Salt",                                  g:   475, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",                 g:  7000, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "PREP — DAY BEFORE",    detail: "Soak MG grain mix overnight." },
      { phase: "MIX",                   detail: "Speed 1: 4 min → Speed 2: 10 min. ~26°C." },
      { phase: "BULK PROOF",            detail: "7500g balls. First fold, 1h AT. Second fold, fridge overnight." },
      { phase: "DIVISION & PRESHAPING", detail: "20 pcs / 375g per baguette. Preshape, relax 15–30 min." },
      { phase: "SHAPING",               detail: "Baguette moulder — 14/tray. Scoring: 2 slashes." },
      { phase: "FINAL PROOF",           detail: "30 min to 1h AT." },
      { phase: "FREEZING",              detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 8. Country Rye Loaf ───────────────────────────────────────────────────
  {
    id:            "country-rye",
    name:          "Country Rye Loaf",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 700,
    base_units:    80,
    unit_label:    "loaves",
    note:          null,
    ingredients: [
      { name: "Organic white flour",    g: 20000, is_flour: true,  is_topping: false },
      { name: "Rye organic flour",      g:  8800, is_flour: false, is_topping: false },
      { name: "Water",                  g: 18700, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   630, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  8000, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 4 min → Speed 2: 8 min. ~26°C." },
      { phase: "BULK PROOF",   detail: "Boxes. First fold, 1h AT. Second fold, fridge overnight." },
      { phase: "DIVISION",     detail: "10 pcs / 700g per loaf. No preshape." },
      { phase: "SHAPING",      detail: "Hand shaped — 10 loaves per tray." },
      { phase: "FINAL PROOF",  detail: "Overnight in fridge. Scoring: 3 slashes." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 9. Wholewheat Loaf ────────────────────────────────────────────────────
  {
    id:            "wholewheat",
    name:          "Wholewheat Loaf",
    category:      "Bread",
    mixer:         "large",
    base_flour:    20000,
    grams_per_unit: 600,
    base_units:    77,
    unit_label:    "loaves",
    note:          null,
    ingredients: [
      { name: "Wholewheat flour",       g: 20000, is_flour: true,  is_topping: false },
      { name: "Organic white flour",    g:  4000, is_flour: false, is_topping: false },
      { name: "Water",                  g: 14300, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   530, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  7200, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 4 min → Speed 2: 8 min. ~26°C." },
      { phase: "BULK PROOF",   detail: "Boxes. First fold, 1h AT. Second fold, fridge overnight." },
      { phase: "DIVISION",     detail: "10 pcs / 600g per loaf." },
      { phase: "SHAPING",      detail: "Hand shaped — 10 loaves per tray." },
      { phase: "FINAL PROOF",  detail: "Overnight in fridge. Scoring: 1 slash." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 10. Pizza Dough ───────────────────────────────────────────────────────
  {
    id:            "pizza",
    name:          "Pizza Dough",
    category:      "Bread",
    mixer:         "large",
    base_flour:    25000,
    grams_per_unit: 300,
    base_units:    166,
    unit_label:    "pizzas",
    note:          null,
    ingredients: [
      { name: "Caputo 00 flour",        g: 25000, is_flour: true,  is_topping: false },
      { name: "Water",                  g: 17500, is_flour: false, is_topping: false },
      { name: "Salt",                   g:   530, is_flour: false, is_topping: false },
      { name: "Levain (ready to use)",  g:  6700, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 4 min → Speed 2: 6:30 min. ~26°C." },
      { phase: "BULK PROOF",   detail: "6000g boxes. First fold, 1h AT. Second fold, fridge overnight." },
      { phase: "DIVISION",     detail: "20 pcs / 300g per pizza." },
      { phase: "SHAPING",      detail: "Hand shaped — 20/tray." },
      { phase: "FINAL PROOF",  detail: "30 min to 1h AT. No scoring." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 11. Brioche Bun ───────────────────────────────────────────────────────
  {
    id:            "brioche-bun",
    name:          "Brioche Bun",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    11340,
    grams_per_unit: 150,
    base_units:    174,
    unit_label:    "buns",
    note:          null,
    ingredients: [
      { name: "Sun Peak flour",       g: 11340, is_flour: true,  is_topping: false },
      { name: "Sugar",                g:  2250, is_flour: false, is_topping: false },
      { name: "Salt",                 g:   200, is_flour: false, is_topping: false },
      { name: "Levain",               g:  1700, is_flour: false, is_topping: false },
      { name: "Fresh yeast",          g:   450, is_flour: false, is_topping: false },
      { name: "Powder milk",          g:   115, is_flour: false, is_topping: false },
      { name: "Water",                g:  1000, is_flour: false, is_topping: false },
      { name: "Eggs",                 g:  5650, is_flour: false, is_topping: false },
      { name: "Vanilla extract",      g:   135, is_flour: false, is_topping: false },
      { name: "Orange blossom water", g:   135, is_flour: false, is_topping: false },
      { name: "Unsalted butter CA",   g:  3180, is_flour: false, is_topping: false },
      { name: "Eggs (egg wash)",      g:  1150, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 3 min → Speed 2 until gluten network forms. Add butter on Speed 2 at ~8 min. Divide in 13kg boxes." },
      { phase: "BULK PROOF",   detail: "20 min at AT, then 2h at 4°C." },
      { phase: "DIVISION",     detail: "150g per bun; 3 × 150g for braided brioche." },
      { phase: "SHAPING",      detail: "Braided (3 cylinders) or balls. Egg wash. No scoring. 14 braided/tray (2×7) or 30 buns/tray (5×6)." },
      { phase: "FINAL PROOF",  detail: "1h–2h in proofing cabinet or hot water rack." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 11b. Braided Brioche ──────────────────────────────────────────────────
  {
    id:            "braided-brioche",
    name:          "Braided Brioche",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    11340,
    grams_per_unit: 450,
    base_units:    58,
    unit_label:    "loaves",
    note:          "Same dough as Brioche Buns. Each braided loaf = 3 × 150g cylinders (450g total). Tray: 14 loaves (2×7).",
    ingredients: [
      { name: "Sun Peak flour",       g: 11340, is_flour: true,  is_topping: false },
      { name: "Sugar",                g:  2250, is_flour: false, is_topping: false },
      { name: "Salt",                 g:   200, is_flour: false, is_topping: false },
      { name: "Levain",               g:  1700, is_flour: false, is_topping: false },
      { name: "Fresh yeast",          g:   450, is_flour: false, is_topping: false },
      { name: "Powder milk",          g:   115, is_flour: false, is_topping: false },
      { name: "Water",                g:  1000, is_flour: false, is_topping: false },
      { name: "Eggs",                 g:  5650, is_flour: false, is_topping: false },
      { name: "Vanilla extract",      g:   135, is_flour: false, is_topping: false },
      { name: "Orange blossom water", g:   135, is_flour: false, is_topping: false },
      { name: "Unsalted butter CA",   g:  3180, is_flour: false, is_topping: false },
      { name: "Eggs (egg wash)",      g:  1150, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 3 min → Speed 2 until gluten network forms. Add butter on Speed 2 at ~8 min. Divide in 13 kg boxes." },
      { phase: "BULK PROOF",   detail: "20 min at AT, then 2h at 4°C." },
      { phase: "DIVISION",     detail: "3 × 150g cylinders per loaf (450g total). Roll into even strands." },
      { phase: "SHAPING",      detail: "Braid 3 strands. Egg wash. No scoring. 14 loaves/tray (2×7)." },
      { phase: "FINAL PROOF",  detail: "1h–2h in proofing cabinet or hot water rack." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 12. Viennoise ─────────────────────────────────────────────────────────
  {
    id:            "viennoise",
    name:          "Viennoise",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    11340,
    grams_per_unit: 200,
    base_units:    100,
    unit_label:    "viennoises",
    note:          null,
    ingredients: [
      { name: "SunPeak flour",       g: 11340, is_flour: true,  is_topping: false },
      { name: "Sugar",               g:   950, is_flour: false, is_topping: false },
      { name: "Salt",                g:   200, is_flour: false, is_topping: false },
      { name: "Levain",              g:   750, is_flour: false, is_topping: false },
      { name: "Fresh yeast",         g:   285, is_flour: false, is_topping: false },
      { name: "Water",               g:  4300, is_flour: false, is_topping: false },
      { name: "Powder milk",         g:   265, is_flour: false, is_topping: false },
      { name: "Eggs",                g:  1135, is_flour: false, is_topping: false },
      { name: "Unsalted butter CA",  g:  1135, is_flour: false, is_topping: false },
      { name: "Eggs (egg wash)",     g:   375, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",          detail: "Speed 1: 3 min. Add butter on Speed 2 at ~4 min. 10kg per box." },
      { phase: "BULK PROOF",   detail: "20 min at AT, then 2h at 4°C." },
      { phase: "DIVISION",     detail: "Hand dividing — 200g per piece. No preshape." },
      { phase: "SHAPING",      detail: "Shaped like baguette. Egg wash. Up to 5 slashes. 16/tray (2×8)." },
      { phase: "FINAL PROOF",  detail: "1h–2h in proofing cabinet." },
      { phase: "FREEZING",     detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 13. Pain au Chocolat ──────────────────────────────────────────────────
  {
    id:            "pac",
    name:          "Pain au Chocolat",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    2050,
    grams_per_unit: null,
    base_units:    25,
    unit_label:    "PAC",
    note:          "Recipe is per paton (3600g dough). Scale by number of patons = ceil(units / 25).",
    ingredients: [
      { name: "Sun Peak flour",       g: 2050, is_flour: true,  is_topping: false },
      { name: "Salt",                 g:   36, is_flour: false, is_topping: false },
      { name: "Sugar",                g:  300, is_flour: false, is_topping: false },
      { name: "Fresh yeast (-5% in summer)", g: 80, is_flour: false, is_topping: false },
      { name: "Levain",               g:  150, is_flour: false, is_topping: false },
      { name: "Butter CA",            g:  100, is_flour: false, is_topping: false },
      { name: "Eggs",                 g:  100, is_flour: false, is_topping: false },
      { name: "Water",                g:  750, is_flour: false, is_topping: false },
      { name: "Powder milk",          g:   50, is_flour: false, is_topping: false },
      { name: "Laminating butter NZ", g: 1000, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",        detail: "Speed 1: 3 min → Speed 2: 4–4:30 min. Divide 3600g/paton." },
      { phase: "BULK PROOF", detail: "Flatten ~60cm × 30cm. Freeze 30 min." },
      { phase: "LAMINATION", detail: "Double fold × 2. Freezer 30–40 min between folds. Fridge as needed." },
      { phase: "SHAPING",    detail: "6mm final lamination. Cut 8cm × 15cm rectangles. 25/tray (5×5). Mini PAC: 88/tray (8×11)." },
      { phase: "FINAL PROOF",detail: "Egg wash with sugar. 2h+." },
      { phase: "FREEZING",   detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 14. Croissant ─────────────────────────────────────────────────────────
  {
    id:            "croissant",
    name:          "Croissant",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    2050,
    grams_per_unit: null,
    base_units:    25,
    unit_label:    "croissants",
    note:          "Same dough as PAC. Laminating butter added at lamination.",
    ingredients: [
      { name: "Sun Peak flour",       g: 2050, is_flour: true,  is_topping: false },
      { name: "Salt",                 g:   36, is_flour: false, is_topping: false },
      { name: "Sugar",                g:  300, is_flour: false, is_topping: false },
      { name: "Fresh yeast (-5% in summer)", g: 80, is_flour: false, is_topping: false },
      { name: "Levain",               g:  150, is_flour: false, is_topping: false },
      { name: "Butter CA",            g:  100, is_flour: false, is_topping: false },
      { name: "Eggs",                 g:  100, is_flour: false, is_topping: false },
      { name: "Water",                g:  750, is_flour: false, is_topping: false },
      { name: "Powder milk",          g:   50, is_flour: false, is_topping: false },
      { name: "Laminating butter NZ", g: 1000, is_flour: false, is_topping: true  },
    ],
    steps: [
      { phase: "MIX",        detail: "Speed 1: 3 min → Speed 2: 4–4:30 min. Divide 3600g/paton." },
      { phase: "BULK PROOF", detail: "Flatten ~60cm × 30cm. Freeze 30 min." },
      { phase: "LAMINATION", detail: "Double fold × 2. Freezer 30–40 min between folds. Fridge as needed." },
      { phase: "SHAPING",    detail: "5.5mm final lamination. Cut 10cm × 27cm triangles. 25/tray (5×5). Mini CR: 63/tray (7×9)." },
      { phase: "FINAL PROOF",detail: "Egg wash with sugar. 2h+." },
      { phase: "FREEZING",   detail: "Min. 12h at −18°C." },
    ],
  },

  // ── 15. Liège Waffle ──────────────────────────────────────────────────────
  {
    id:            "waffle",
    name:          "Liège Waffle",
    category:      "Pastry",
    mixer:         "small",
    base_flour:    11340,
    grams_per_unit: 100,
    base_units:    317,
    unit_label:    "waffles",
    note:          null,
    ingredients: [
      { name: "Sun Peak Flour",      g: 11340, is_flour: true,  is_topping: false },
      { name: "Sugar",               g:   680, is_flour: false, is_topping: false },
      { name: "Pearl sugar",         g:  5670, is_flour: false, is_topping: false },
      { name: "Salt",                g:    96, is_flour: false, is_topping: false },
      { name: "Fresh yeast",         g:   227, is_flour: false, is_topping: false },
      { name: "Powder milk",         g:   499, is_flour: false, is_topping: false },
      { name: "Water",               g:  4491, is_flour: false, is_topping: false },
      { name: "Eggs",                g:  2268, is_flour: false, is_topping: false },
      { name: "Unsalted butter CA",  g:  6464, is_flour: false, is_topping: false },
    ],
    steps: [
      { phase: "MIX",       detail: "Speed 1: 3 min → Speed 2: 5+ min until gluten network forms. Add butter in 2 stages. Max dough temp: 28°C." },
      { phase: "BULK PROOF",detail: "1h at 24–28°C. Add pearl sugar after proofing, mix 1 min." },
      { phase: "DIVISION",  detail: "100g balls. Roll in icing sugar." },
      { phase: "BAKING",    detail: "Bake until golden (no burnt areas). Cool on parchment 1h. 48/tray (2×24)." },
      { phase: "FREEZING",  detail: "Cool in fridge first. Seal in plastic pouch (pack of 3). Min. 12h at −18°C." },
    ],
  },

];
